class Error(Exception):
    pass

class ValidatingError(Error):
    pass